name: dlima
favicon: null
layout_spectrum: 0.79176
typography_spectrum: 0.53636
title: 'Jornalismo, infografia e adjacências'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1875
  lightness: 0.4476467703934759
  saturation: 0.5625
  rhythmicContrast: 0.9365300403442234
purpose: []
